# Generated by Django 5.2.7 on 2026-04-28 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1077_workflowaction_assign_folder_remove_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='1 = first version ever stored, increments with each supersession.', verbose_name='version number')),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this version was replaced by a newer one.', verbose_name='archived at')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('checksum', models.CharField(max_length=32, verbose_name='checksum')),
                ('archive_checksum', models.CharField(blank=True, max_length=32, null=True, verbose_name='archive checksum')),
                ('original_filename', models.CharField(blank=True, max_length=1024, null=True, verbose_name='original filename')),
                ('mime_type', models.CharField(blank=True, max_length=256, null=True, verbose_name='MIME type')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='page count')),
                ('document_created', models.DateField(blank=True, null=True, verbose_name='document created')),
                ('original_file', models.CharField(help_text='Filename relative to the versions directory.', max_length=2048, verbose_name='original file')),
                ('archive_file', models.CharField(blank=True, help_text='Filename of the archived PDF, if one existed.', max_length=2048, null=True, verbose_name='archive file')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='document')),
            ],
            options={
                'verbose_name': 'document version',
                'verbose_name_plural': 'document versions',
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
